### ISSUE TITLE
Introduce a binstubs config

### ISSUE THREAD

**Issue by fgrehm** [fgrehm/devstep-cli#15]
Lots of custom commands won't require additional docker configs, so we will end up with weird stuff like the code below to generate binstubs:

```yaml
commands:
  foreman:
    publish: ['5000:5000']
  rake:
    # No custom configs
  guard:
    # No custom configs
  rails:
    # No custom configs
```

Instead of using just the `commands` config just to generate binstubs, we can introduce a dedicated config for that, so the `devstep binstubs` command would generate binstubs for the stuff configured for `commands` and `binstubs`:

```yaml
binstubs:
- 'rake'
- 'guard'
- 'rails'
commands:
  foreman:
    publish: ['5000:5000']
```
